# name: Laravel

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   laravel-tests:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2
#       - name: Copy .env
#         run: php -r "file_exists('.env') || copy('.env.example', '.env');"
#       - name: Install Dependencies
#         run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
#       - name: Generate key
#         run: php artisan key:generate
#       - name: Directory Permissions
#         run: chmod -R 777 storage bootstrap/cache

#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Setup Node.js
#         uses: actions/setup-node@v2-beta
#         with:
#           node-version: "16"
#           check-latest: true
#       - name: Install NPM dependencies
#         run: npm install
#       - name: Compile assets for production
#         run: npm run production

#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Deployment
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           username: ${{ secrets.SSH_USERNAME }}
#           script: |
#             cd /var/www/ecommerce-app-v4/
#             git fetch
#             get reset --hard HEAD
#             git checkout -f main
#             git pull
#             composer install --no-dev --optimize-autoloader
#             php artisan optimize
#             php artisan queue:restart

name: Laravel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  laravel:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@master
        with:
          php-version: "8.1"
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Compile Assets
        uses: actions/setup-node@v2
        with:
          node-version: '16'
        run: npm install
        run: npm run prod
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /var/www/ecommerce-app-v4/

